### ISSUE TITLE
Migration can't be rolled back

### ISSUE THREAD

**Issue by felipelincoln** [felipelincoln/branchpage#90]
```
13:50:07.687 [info]  == Running 20210627194434 Publishing.Repo.Migrations.AlterArticleTableRenamePreviewColumn.change/0 backward
** (Ecto.MigrationError) cannot reverse migration command: alter table article. You will need to explicitly define up/0 and down/0 in your migration
    (ecto_sql 3.6.2) lib/ecto/migration/runner.ex:213: Ecto.Migration.Runner.execute_in_direction/5
    (ecto_sql 3.6.2) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir 1.11.4) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.6.2) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    (ecto_sql 3.6.2) lib/ecto/migration/runner.ex:280: Ecto.Migration.Runner.perform_operation/3
    (stdlib 3.14) timer.erl:166: :timer.tc/1
    (ecto_sql 3.6.2) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/8
    (ecto_sql 3.6.2) lib/ecto/migrator.ex:324: Ecto.Migrator.attempt/8
```

**Comment by ryguigas0** [comment]
Hey I can work on that, could you assign me and add the hacktoberfest tag?
